export type Entry={credential_id?:string;id:string;name:string;color:string;provider:string;model?:string;structured_outputs?:boolean;reasoning_effort?:'low'|'non-thinking'|null;abstention_policy?:string;proxy?:boolean;ready?:boolean;enabled?:boolean;requires_invitation?:boolean;access?:string};
export type Seat={id:string;name:string;seat:number;stack:number;bet:number;committed:number;folded:boolean;all_in:boolean;cards:string[];position:string;payoff:number|null};
export type Action={id:string;kind:string;label:string;pay:number;to:number;all_in:boolean};
export type State={hand_number:number;street:string;button:number;actor:string|null;complete:boolean;board:string[];seats:Seat[];pot:number;pots:{amount:number;eligible:string[]}[];small_blind:number;big_blind:number;ante:number;to_call:number;legal_actions:Action[]};
export type Decision={thinking?:string;adapter?:{name:string;version:string};model:string;retry_count?:number;answers:{action:{choice:string;probabilities:Record<string,number>;confidence:number;legal_action_projection?:{abstention_probability:number;choice_changed:boolean;reported_abstention:boolean}}};latency:number;proxy:boolean};
export type GameEvent={index:number;type:string;label:string;action?:Action&{player:string;decision?:Decision;raise_number?:number};snapshot:State};
export type Standing={retired_reason?:string;retired?:boolean;id:string;name:string;stack:number;reserve:number;profit:number;equity:number;rank:number;place:number|null;bb100:number|null;rebuys:number};
export type TimingRow={id:string;name:string;decisions:number;included:number;retry_excluded:number;outlier_excluded:number;invalid_excluded:number;mean_seconds:number|null;median_seconds:number|null;p90_seconds:number|null};
export type Series={id:string;status:string;message:string;target:number;completed:number;current_run_id:string;current_number:number;run_ids:string[];standings:{id:string;name:string;color:string;rank:number|null;completed:number;mean_place:number|null;wins:number}[]};
export type Run={cash_reset_at?:number|null;cash_reset_start_hand?:number|null;chip_rule_start_hand?:number;billing_mode?:'hosted'|'personal';pending_kicks?:string[];human_player_id?:string|null;series_id?:string|null;series_number?:number|null;settle_every?:number;buy_in?:number;timing?:{method:string;models:TimingRow[]};highlights?:{hand:number;reasons:string[];pot:number;pot_bb:number;eliminations:string[]}[];llm_adapter?:{name:string;version?:string};id:string;created:number;provider_retries?:number;name:string;mode:'cash'|'sng';status:string;message:string;hands_played:number;max_hands:number;active_hand:number|null;orbit:number;proxy:boolean;champion:string|null;entries:Entry[];standings:Standing[];events:{type:string;hand:number;player?:string;amount?:number;label:string}[];history:{hand:number;values:Record<string,number>;ev_values?:Record<string,number>}[];ev_summary?:{covered_hands:number};big_blind:number};
export const money=(n:number,mode:string='cash')=>new Intl.NumberFormat('en-US',{maximumFractionDigits:mode==='cash'?2:0}).format(mode==='cash'?n/100:n);
export const streetName:Record<string,string>={preflop:'翻牌前',flop:'翻牌',turn:'转牌',river:'河牌',complete:'已结算'};
export const statusName:Record<string,string>={ready:'待开始',running:'进行中',pausing:'正在暂停',waiting_human:'等待你行动',waiting_next_hand:'等待下一手',paused:'已暂停',complete:'已完成',hand_limit:'试跑结束',error:'需要检查',bankroll_limit:'资金不足'};
export {api} from './api';

export const seriesPoints=(series:Series,row:Series["standings"][number])=>row.mean_place===null?null:Math.round(row.completed*(series.standings.length-row.mean_place));

export type RoomInput={custom_agents?:import('./customAgents').CustomAgent[];name:string;player_name:string;mode:'cash'|'sng';model_ids:string[];deepseek_thinking:string;max_hands:number;run_budget_cny:number;billing_mode:'hosted'|'personal'};
